[2025-02-21T06:28:50.338+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-21T06:28:50.365+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: google_news_scraper.get_and_parse_articles scheduled__2025-02-20T00:00:00+00:00 [queued]>
[2025-02-21T06:28:50.379+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: google_news_scraper.get_and_parse_articles scheduled__2025-02-20T00:00:00+00:00 [queued]>
[2025-02-21T06:28:50.381+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 3
[2025-02-21T06:28:50.400+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): get_and_parse_articles> on 2025-02-20 00:00:00+00:00
[2025-02-21T06:28:50.413+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1817) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-21T06:28:50.416+0000] {standard_task_runner.py:72} INFO - Started process 1831 to run task
[2025-02-21T06:28:50.416+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'google_news_scraper', 'get_and_parse_articles', 'scheduled__2025-02-20T00:00:00+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/dag2.py', '--cfg-path', '/tmp/tmpfohl4s8r']
[2025-02-21T06:28:50.417+0000] {standard_task_runner.py:105} INFO - Job 51: Subtask get_and_parse_articles
[2025-02-21T06:28:50.486+0000] {task_command.py:467} INFO - Running <TaskInstance: google_news_scraper.get_and_parse_articles scheduled__2025-02-20T00:00:00+00:00 [running]> on host 66d0a4630213
[2025-02-21T06:28:50.602+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='google_news_scraper' AIRFLOW_CTX_TASK_ID='get_and_parse_articles' AIRFLOW_CTX_EXECUTION_DATE='2025-02-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-20T00:00:00+00:00'
[2025-02-21T06:28:50.604+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-21T06:28:50.605+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-21T06:28:50.606+0000] {logging_mixin.py:190} INFO - Current task name:get_and_parse_articles state:running start_date:2025-02-21 06:28:50.366185+00:00
[2025-02-21T06:28:50.606+0000] {logging_mixin.py:190} INFO - Dag name:google_news_scraper and current dag run status:running
[2025-02-21T06:28:50.607+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-21T06:28:51.545+0000] {logging_mixin.py:190} INFO - https://news.google.com/read/CBMi4wFBVV95cUxPMzVmcjVreURGZ0hteW5BbEozRkJ2R2NBUWw2c1Y0QVMwaFVIdkQ0NWM3WmxDMG5yRGhfc2ZaUDg0VlMyYjQxbXQxckVGOG41VTVsbUI0a3pQYm56c0RxU3pCRWkyUW5YWklCWE5tRDRpQkVuNHNkX1hUcF9Hd1VzVzh6NGpYdEc3NjFUOE93QXNYMkQtNE5wcUp2Q0xrdU1admp6QklYUER5VVZVNHhDU1FlUHBSV1ZhZzlOdVJoR3NMTnVQWXhYbjJuOW8wWG1zaUMwclFPS1BKUmFROUROTmVKZ9IB6AFBVV95cUxNa1NqTjNEUG9IM1I2TVlfT1JKWGRlTFB0WmlJZnZSS1VWdWIxY29ITzdGYU9uS0dxR1VVYU5DaEpMOXBJcjMyNWFKUWlfbU9zdUpDZ0VERkhfWXo0Y01KUU5WZ0x0UDBYSENXNGIwMVBPcC0tN1RPODVONU9DV0pyeWRYZS05QzlheU5RSHRuRmg3QjRiUktWMGEySUVQV2ljaWxnSm13OVpxTmlPY05WZDlWMFgwRjhzVml2V0JXZVlqREpEVVpGeHU5aU5IakZYWkN1S1pGWk1jRURvZV9ZZXRjSzg5bjJI?hl=en-IN&gl=IN&ceid=IN%3Aen
[2025-02-21T06:28:51.547+0000] {logger.py:11} INFO - ====== WebDriver manager ======
[2025-02-21T06:28:51.568+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-02-21T06:28:51.838+0000] {logger.py:11} INFO - About to download new driver from https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
[2025-02-21T06:28:51.988+0000] {logger.py:11} INFO - Driver downloading response is 200
[2025-02-21T06:28:52.791+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-02-21T06:28:53.162+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-02-21T06:28:53.392+0000] {logger.py:11} INFO - Driver has been saved in cache [/home/***/.wdm/drivers/chromedriver/linux64/114.0.5735.90]
[2025-02-21T06:28:53.409+0000] {logging_mixin.py:190} INFO - Error with Selenium: Message: Service /home/***/.wdm/drivers/chromedriver/linux64/114.0.5735.90/chromedriver unexpectedly exited. Status code was: 127
[2025-02-21T06:28:53.686+0000] {logging_mixin.py:190} INFO - [INFO] Downloaded thumbnail: thumbnail_22.jpg
[2025-02-21T06:28:53.697+0000] {logging_mixin.py:190} INFO - New article added with ID: 22
[2025-02-21T06:28:53.698+0000] {logging_mixin.py:190} INFO - https://news.google.com/read/CBMiwwFBVV95cUxPX09zMDFXTGVDU2hHSzcwVF9PRS00LUYwdHdJWW15TkcwcTZaWUFpNnFDei1Wd1h5MVR4QXJhenVRTUp4Vnp6eFlLV2FwS3psUDRIRnFlY0dxQjVwUDJmSExwTGZNN2NMYTJsYXg5eUZvX1FRYTdndzZiWlc5eG5HN3VYNUVBZkwzWjZ5dVJ3MnF6UlB5cWt3c2RXNEp5R0dHXzlJcENla1FSN3VVT2xwWFRncks0M1RYd1NoOXVkT1FGWHM?hl=en-IN&gl=IN&ceid=IN%3Aen
[2025-02-21T06:28:53.699+0000] {logger.py:11} INFO - ====== WebDriver manager ======
[2025-02-21T06:28:53.722+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-02-21T06:28:54.085+0000] {logger.py:11} INFO - About to download new driver from https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
[2025-02-21T06:28:54.372+0000] {logger.py:11} INFO - Driver downloading response is 200
[2025-02-21T06:28:55.516+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-02-21T06:28:55.927+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-02-21T06:28:56.371+0000] {logger.py:11} INFO - Driver has been saved in cache [/home/***/.wdm/drivers/chromedriver/linux64/114.0.5735.90]
[2025-02-21T06:28:56.384+0000] {logging_mixin.py:190} INFO - Error with Selenium: Message: Service /home/***/.wdm/drivers/chromedriver/linux64/114.0.5735.90/chromedriver unexpectedly exited. Status code was: 127
[2025-02-21T06:28:56.756+0000] {logging_mixin.py:190} INFO - [INFO] Downloaded thumbnail: thumbnail_23.jpg
[2025-02-21T06:28:56.761+0000] {logging_mixin.py:190} INFO - New article added with ID: 23
[2025-02-21T06:28:56.762+0000] {logging_mixin.py:190} INFO - https://news.google.com/read/CBMiwAFBVV95cUxNMUtFLUVacFJQX0lYYkRnd194SGdQNi05aklHcVYzYVhrelJ5aEMyZmxFNjhQa0lRNGRKdktreTF2UWk5aTBGRnBIRzRKd2p2ZFN0QXphQWlFaFFIT0VicjFjLVcwbUpHS0hVcG1rVkh3NTR1emdQQW16N2k1MFY0TS1VR3YzcHJDX3NGZmpOM0xRTmNVNWpWMjN0T0ZhOExVcktuVEVwcU5na2J5Y3lFcHpKaHJBZXRxOXZfVWZsb0LSAccBQVVfeXFMTkpKbkJzYXNJLW9Wanl1SVV4V3JBTEVveTkzUVYxUVBqOE9mSHpqa3Q0OHdmSzd6MUswOXU1cjIxdk5obEhRQW56M2VYV3htVngzQnFRRklRS1lBcDVpTGRJVzUzazQ3cVNhZ3dLbVVpemt4WXl3VmpMWjhTQ3hlNVFLLUJNRDFqUVpPYlgzUzlNMktJc2drWldna3ZYMk5WX09IenBEbk5wb0V0QjdEOEhZTkJZdENFRVZYeHg3NE10S2ROMThWVQ?hl=en-IN&gl=IN&ceid=IN%3Aen
[2025-02-21T06:28:56.763+0000] {logger.py:11} INFO - ====== WebDriver manager ======
[2025-02-21T06:28:56.785+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-02-21T06:28:57.120+0000] {logger.py:11} INFO - About to download new driver from https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
[2025-02-21T06:28:57.476+0000] {logger.py:11} INFO - Driver downloading response is 200
[2025-02-21T06:28:58.613+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-02-21T06:28:58.924+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-02-21T06:28:59.116+0000] {logger.py:11} INFO - Driver has been saved in cache [/home/***/.wdm/drivers/chromedriver/linux64/114.0.5735.90]
[2025-02-21T06:28:59.129+0000] {logging_mixin.py:190} INFO - Error with Selenium: Message: Service /home/***/.wdm/drivers/chromedriver/linux64/114.0.5735.90/chromedriver unexpectedly exited. Status code was: 127
[2025-02-21T06:28:59.341+0000] {logging_mixin.py:190} INFO - [INFO] Downloaded thumbnail: thumbnail_24.jpg
[2025-02-21T06:28:59.346+0000] {logging_mixin.py:190} INFO - New article added with ID: 24
[2025-02-21T06:28:59.347+0000] {logging_mixin.py:190} INFO - https://news.google.com/read/CBMi8AFBVV95cUxNcFNjaFBZSzYza2s1STljaUlXT0lqOXlYVFhXeGd2S2JVSTN5bWc1RE1VTXRGMnRfdW5TRGdzdWFMeTlURDI2VmZRZFN5Nl9RbGxVNG80YTAyQ2F2aGw0dzN5YVpwQ0IzZy1OajVGS0JhLXlXQWFwVEtJYk5Ic21lbVFkc05MNmQ3Rm04SG54U3hRVUplR1lBOVIwdkRtbUZPSHdzelhSbkVKZk1XVzRMNTRwTmFTLW1FTmRwZzN6cUFKN0ZJQ0U3R0VxbDNHV0FVeGhmdDRFMWdkMHN2RFctR1g0cE0xTmV3ekFvUDk5TzM?hl=en-IN&gl=IN&ceid=IN%3Aen
[2025-02-21T06:28:59.348+0000] {logger.py:11} INFO - ====== WebDriver manager ======
[2025-02-21T06:28:59.373+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-02-21T06:28:59.572+0000] {logger.py:11} INFO - About to download new driver from https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
[2025-02-21T06:28:59.756+0000] {logger.py:11} INFO - Driver downloading response is 200
[2025-02-21T06:29:00.666+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-02-21T06:29:01.011+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-02-21T06:29:01.222+0000] {logger.py:11} INFO - Driver has been saved in cache [/home/***/.wdm/drivers/chromedriver/linux64/114.0.5735.90]
[2025-02-21T06:29:01.239+0000] {logging_mixin.py:190} INFO - Error with Selenium: Message: Service /home/***/.wdm/drivers/chromedriver/linux64/114.0.5735.90/chromedriver unexpectedly exited. Status code was: 127
[2025-02-21T06:29:01.420+0000] {logging_mixin.py:190} INFO - [INFO] Downloaded thumbnail: thumbnail_25.jpg
[2025-02-21T06:29:01.425+0000] {logging_mixin.py:190} INFO - New article added with ID: 25
[2025-02-21T06:29:01.426+0000] {logging_mixin.py:190} INFO - https://news.google.com/read/CBMiwAFBVV95cUxQWUJsSHNiWWJkU0JvejdMWkxvTzQzX3hvUkxzY19wQkM1Uk84QlR5bXh6TzNqWXRSRFpMZ0R1eTBoQURxdVhJcE93am8zd1dLNi10ZW5VNnI5OV8zLWZXZTdQZkNCbzFJY3VkZXJUcEdxZFp1cHE4dU1fMXpMZXl4MFh5c2Vab2NiOWxFYWZ2eVB3ZzB1NU44SjlnRVRSNC1WSXdRczRaS3NXd0JUdDItY0U5N1YzUDNiTDdxQlF3cmE?hl=en-IN&gl=IN&ceid=IN%3Aen
[2025-02-21T06:29:01.427+0000] {logger.py:11} INFO - ====== WebDriver manager ======
[2025-02-21T06:29:01.460+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-02-21T06:29:01.639+0000] {logger.py:11} INFO - About to download new driver from https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
[2025-02-21T06:29:01.824+0000] {logger.py:11} INFO - Driver downloading response is 200
[2025-02-21T06:29:02.927+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-02-21T06:29:03.288+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-02-21T06:29:03.513+0000] {logger.py:11} INFO - Driver has been saved in cache [/home/***/.wdm/drivers/chromedriver/linux64/114.0.5735.90]
[2025-02-21T06:29:03.527+0000] {logging_mixin.py:190} INFO - Error with Selenium: Message: Service /home/***/.wdm/drivers/chromedriver/linux64/114.0.5735.90/chromedriver unexpectedly exited. Status code was: 127
[2025-02-21T06:29:03.797+0000] {logging_mixin.py:190} INFO - [INFO] Downloaded thumbnail: thumbnail_26.jpg
[2025-02-21T06:29:03.807+0000] {logging_mixin.py:190} INFO - New article added with ID: 26
[2025-02-21T06:29:03.809+0000] {logging_mixin.py:190} INFO - https://news.google.com/read/CBMizwFBVV95cUxNXzU1RW1aNTNRSTJCN3dMOUhadkl0RDFCOFptV09LT1pfeVQ3YjlsekVtWU9fQlI3TURlTW1jME5UdXdSNDY5TjJPbGh5b0lzcmJwUXhpLTl2cmVFS3BVSGcwOWp6ekxIa3FabUZjWURwYTV5MHBEN1RTd000RGU4Tndod2puYTVzY2hHUlotLUJDS1pHLVAyM25zWHJINXFjVjRsamVTcjZZMVVuVUxIVkVIUHlVTHo3cHItSElnTjFCc2NhZ2oyU0tMeVpRcDQ?hl=en-IN&gl=IN&ceid=IN%3Aen
[2025-02-21T06:29:03.810+0000] {logger.py:11} INFO - ====== WebDriver manager ======
[2025-02-21T06:29:03.849+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-02-21T06:29:04.051+0000] {logger.py:11} INFO - About to download new driver from https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
[2025-02-21T06:29:04.217+0000] {logger.py:11} INFO - Driver downloading response is 200
[2025-02-21T06:29:05.238+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-02-21T06:29:05.559+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-02-21T06:29:05.744+0000] {logger.py:11} INFO - Driver has been saved in cache [/home/***/.wdm/drivers/chromedriver/linux64/114.0.5735.90]
[2025-02-21T06:29:05.759+0000] {logging_mixin.py:190} INFO - Error with Selenium: Message: Service /home/***/.wdm/drivers/chromedriver/linux64/114.0.5735.90/chromedriver unexpectedly exited. Status code was: 127
[2025-02-21T06:29:05.955+0000] {logging_mixin.py:190} INFO - [INFO] Downloaded thumbnail: thumbnail_27.jpg
[2025-02-21T06:29:05.963+0000] {logging_mixin.py:190} INFO - New article added with ID: 27
[2025-02-21T06:29:05.965+0000] {logging_mixin.py:190} INFO - https://news.google.com/read/CBMi1wFBVV95cUxOQTlpOHNIRFI1VVlPX0JKOFZPYkZmV1BtaEVyU2xmVlhYM0txNnhnSVlVVFVleVFIcDdMYmJPVDUyYTNweVBfS2FDbF9saGlUV1JQV0NpS0xRMUtySkVNQlNKTExNN1kzTGx5M29xcjhhV1hpc01wRDVHTENxaGE0RUt3emZtSkxjVC1ScU5FdHFZTmdPSVM3WmRvRVA4VjJraTNXaExBTWhXalU5b29CSlNaSExxZHNnU3ZMSmdNa205S1dLWFBOQ09PeU9CMWY2UVROeFJhd9IB3gFBVV95cUxNQ2JFTDBTbnBmWVRvMzF4WW04Z2JnRDFZMWFqQV9GaXd1Y1hWbTEzUzJrNXJqblcza1FSbXFtaDA1UkF0UWxOTWRrOVp1RW9lM1RQcHdybXIxcVVZZ3lGamVnajB6dm5zaUZDVkFORXljRTJjU0t3bXNVVURtQ1BaZFFsUlhvZXdaMUJoRWVDbk1tb08yRkNuOWdVSWFIbkZXUkdhVnZNaVBiSVZYUW1DR05UT0tXVmQ5MVVzeEtNMHhSVlJkQWhiYVpHcmNiWW51Z19PU0d3R3B4d3EwQkE?hl=en-IN&gl=IN&ceid=IN%3Aen
[2025-02-21T06:29:05.966+0000] {logger.py:11} INFO - ====== WebDriver manager ======
[2025-02-21T06:29:05.995+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-02-21T06:29:06.174+0000] {logger.py:11} INFO - About to download new driver from https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
[2025-02-21T06:29:06.366+0000] {logger.py:11} INFO - Driver downloading response is 200
[2025-02-21T06:29:07.232+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-02-21T06:29:06.503+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-02-21T06:29:06.694+0000] {logger.py:11} INFO - Driver has been saved in cache [/home/***/.wdm/drivers/chromedriver/linux64/114.0.5735.90]
[2025-02-21T06:29:06.707+0000] {logging_mixin.py:190} INFO - Error with Selenium: Message: Service /home/***/.wdm/drivers/chromedriver/linux64/114.0.5735.90/chromedriver unexpectedly exited. Status code was: 127
[2025-02-21T06:29:06.901+0000] {logging_mixin.py:190} INFO - [INFO] Downloaded thumbnail: thumbnail_28.jpg
[2025-02-21T06:29:06.907+0000] {logging_mixin.py:190} INFO - New article added with ID: 28
[2025-02-21T06:29:06.908+0000] {logging_mixin.py:190} INFO - https://news.google.com/read/CBMi5AFBVV95cUxPekE1NUx6MU5vS1BGV3JXVlViRVRsb3NfZERDRXByYnFKVnozLVZJTURLTUE4VWhGVGk0a0gzYzRJLWROTzRublZqZU9vZjlUNjY3eVp4T2UwdHQyUUQyd0FqQVhRUTdEc05ud0lIQWVLdkRhVTNqRFQ0RFFCcnFHMkQ2dzZzandBekpLZjdiSnBrNzRnVS1aNXp6SFVsUjVfTnhyNWxMbHhFcV9xYU5id0lfbElpV3M1eXp2SHVHQjd6ZW1wYzM4akU1bWt6d0wxallJbE05bloxRkVGbVJxaXVQem3SAeoBQVVfeXFMTmdrcjZNdmxyWGhzVV9NZXFwRXllaGJ2QTV4al9xOV9GclkzZ0Z5QmN0d1B2Rmt1c1UwVm5ib0wwZzh6MjV1bTYzLUZONl9pa0NzUEZaMGtkNkFjRlBzTGZ4WlVtSEFSd3RZYlNVNHY0TnJZaXA4dGExcHBUT1Y2VzV6Zy1PdnBfYkZJRU9kTHNRZkh6LVVPUkQ3elV3Q3RhanF5Z21zR3ZIbTE2cjNyb0JVeWFVYTdLaldCYnRJSVgxVFlBRU1JQWlSSENPSTdZc0tRcnJsNGhTZlpRY3YxVzROa29udHBDWGp3?hl=en-IN&gl=IN&ceid=IN%3Aen
[2025-02-21T06:29:06.910+0000] {logger.py:11} INFO - ====== WebDriver manager ======
[2025-02-21T06:29:06.936+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-02-21T06:29:07.088+0000] {logger.py:11} INFO - About to download new driver from https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
[2025-02-21T06:29:07.272+0000] {logger.py:11} INFO - Driver downloading response is 200
[2025-02-21T06:29:08.043+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-02-21T06:29:08.400+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-02-21T06:29:08.581+0000] {logger.py:11} INFO - Driver has been saved in cache [/home/***/.wdm/drivers/chromedriver/linux64/114.0.5735.90]
[2025-02-21T06:29:08.596+0000] {logging_mixin.py:190} INFO - Error with Selenium: Message: Service /home/***/.wdm/drivers/chromedriver/linux64/114.0.5735.90/chromedriver unexpectedly exited. Status code was: 127
[2025-02-21T06:29:08.757+0000] {logging_mixin.py:190} INFO - [INFO] Downloaded thumbnail: thumbnail_29.jpg
[2025-02-21T06:29:08.762+0000] {logging_mixin.py:190} INFO - New article added with ID: 29
[2025-02-21T06:29:08.787+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-21T06:29:08.807+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-21T06:29:08.809+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=google_news_scraper, task_id=get_and_parse_articles, run_id=scheduled__2025-02-20T00:00:00+00:00, execution_date=20250220T000000, start_date=20250221T062850, end_date=20250221T062908
[2025-02-21T06:29:08.851+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-21T06:29:08.852+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-21T06:29:08.853+0000] {logging_mixin.py:190} INFO - Dag name:google_news_scraper queued_at:2025-02-21 06:28:35.381348+00:00
[2025-02-21T06:29:08.854+0000] {logging_mixin.py:190} INFO - Task hostname:66d0a4630213 operator:PythonOperator
[2025-02-21T06:29:08.894+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-21T06:29:08.927+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-21T06:29:08.930+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
